export const SUPPLY_CHAIN_ADDRESSES = {
    MAYORISTA: process.env.NEXT_PUBLIC_PARTICIPANTE_MAYORISTA?.toLowerCase(),
    TRANSPORTISTA: process.env.NEXT_PUBLIC_PARTICIPANTE_TRANSPORTISTA?.toLowerCase(),
    PUNTO_VENTA: process.env.NEXT_PUBLIC_PARTICIPANTE_PUNTOVENTA?.toLowerCase(),
}