export const SUPPLY_CHAIN_ADDRESSES = {
    MAYORISTA: process.env.NEXT_PUBLIC_PARTICIPANTE_ENLATADO?.toLowerCase(),
    TRANSPORTISTA: process.env.NEXT_PUBLIC_PARTICIPANTE_DISTRIBUCION?.toLowerCase(),
    PUNTO_VENTA: process.env.NEXT_PUBLIC_PARTICIPANTE_PUNTOVENTA?.toLowerCase(),
}