export const SUPPLY_CHAIN_ADDRESSES = {
    ENLATADO: process.env.NEXT_PUBLIC_PARTICIPANTE_ENLATADO?.toLowerCase(),
    DISTRIBUCION: process.env.NEXT_PUBLIC_PARTICIPANTE_DISTRIBUCION?.toLowerCase(),
    PUNTO_VENTA: process.env.NEXT_PUBLIC_PARTICIPANTE_PUNTOVENTA?.toLowerCase(),
}